[package]
name = "rusty_snake"
version = "1.0.0"
edition = "2021"
authors = ["Tanav Malhotra"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.5"
piston_window = "0.131.0"
